#[path = "Block.rs"]
pub mod Block;
#[path = "BlockMiningData.rs"]
pub mod BlockMiningData;
pub mod material;
pub mod state;

#[path = "BlockButton.rs"]
pub mod BlockButton;
#[path = "BlockDoor.rs"]
pub mod BlockDoor;
#[path = "BlockEndRod.rs"]
pub mod BlockEndRod;
#[path = "BlockFence.rs"]
pub mod BlockFence;
#[path = "BlockFenceGate.rs"]
pub mod BlockFenceGate;
#[path = "BlockLadder.rs"]
pub mod BlockLadder;
#[path = "BlockLever.rs"]
pub mod BlockLever;
#[path = "BlockLiquid.rs"]
pub mod BlockLiquid;
#[path = "BlockPane.rs"]
pub mod BlockPane;
#[path = "BlockRailBase.rs"]
pub mod BlockRailBase;
#[path = "BlockSign.rs"]
pub mod BlockSign;
#[path = "BlockSlab.rs"]
pub mod BlockSlab;
#[path = "BlockStairs.rs"]
pub mod BlockStairs;
#[path = "BlockTorch.rs"]
pub mod BlockTorch;
#[path = "BlockTrapDoor.rs"]
pub mod BlockTrapDoor;
#[path = "BlockWall.rs"]
pub mod BlockWall;

#[path = "BlockEndPortalFrame.rs"]
pub mod BlockEndPortalFrame;
#[path = "BlockSkull.rs"]
pub mod BlockSkull;
#[path = "BlockVine.rs"]
pub mod BlockVine;

#[path = "BlockSlime.rs"]
pub mod BlockSlime;
#[path = "BlockWeb.rs"]
pub mod BlockWeb;

#[path = "BlockBed.rs"]
pub mod BlockBed;

#[path = "BlockFire.rs"]
pub mod BlockFire;

#[path = "BlockFlowerPot.rs"]
pub mod BlockFlowerPot;
#[path = "BlockJukebox.rs"]
pub mod BlockJukebox;
#[path = "BlockPistonBase.rs"]
pub mod BlockPistonBase;
#[path = "BlockPistonExtension.rs"]
pub mod BlockPistonExtension;
#[path = "BlockRedstoneComparator.rs"]
pub mod BlockRedstoneComparator;
#[path = "BlockRedstoneRepeater.rs"]
pub mod BlockRedstoneRepeater;
#[path = "BlockRedstoneWire.rs"]
pub mod BlockRedstoneWire;

#[path = "BlockAnvil.rs"]
pub mod BlockAnvil;
#[path = "BlockGlazedTerracotta.rs"]
pub mod BlockGlazedTerracotta;
#[path = "BlockLog.rs"]
pub mod BlockLog;
#[path = "BlockPumpkin.rs"]
pub mod BlockPumpkin;
#[path = "BlockQuartz.rs"]
pub mod BlockQuartz;
#[path = "BlockRotatedPillar.rs"]
pub mod BlockRotatedPillar;
#[path = "SoundType.rs"]
pub mod SoundType;
