#[path = "TileEntity.rs"]
pub mod TileEntity;
#[path = "TileEntityBed.rs"]
pub mod TileEntityBed;
#[path = "TileEntityChest.rs"]
pub mod TileEntityChest;
#[path = "TileEntityEnchantmentTable.rs"]
pub mod TileEntityEnchantmentTable;
#[path = "TileEntityEnderChest.rs"]
pub mod TileEntityEnderChest;
#[path = "TileEntityPiston.rs"]
pub mod TileEntityPiston;
#[path = "TileEntityShulkerBox.rs"]
pub mod TileEntityShulkerBox;
#[path = "TileEntitySign.rs"]
pub mod TileEntitySign;
#[path = "TileEntitySkull.rs"]
pub mod TileEntitySkull;

#[path = "TileEntityBeacon.rs"]
pub mod TileEntityBeacon;
#[path = "TileEntityEndPortal.rs"]
pub mod TileEntityEndPortal;
#[path = "TileEntityFlowerPot.rs"]
pub mod TileEntityFlowerPot;
