#[path = "SPacketAnimation.rs"]
pub mod SPacketAnimation;
#[path = "SPacketBlockAction.rs"]
pub mod SPacketBlockAction;
#[path = "SPacketBlockBreakAnim.rs"]
pub mod SPacketBlockBreakAnim;
#[path = "SPacketBlockChange.rs"]
pub mod SPacketBlockChange;
#[path = "SPacketChunkData.rs"]
pub mod SPacketChunkData;
#[path = "SPacketCloseWindow.rs"]
pub mod SPacketCloseWindow;
#[path = "SPacketCooldown.rs"]
pub mod SPacketCooldown;
#[path = "SPacketDestroyEntities.rs"]
pub mod SPacketDestroyEntities;
#[path = "SPacketDisconnect.rs"]
pub mod SPacketDisconnect;
#[path = "SPacketEntity.rs"]
pub mod SPacketEntity;
#[path = "SPacketEntityAttach.rs"]
pub mod SPacketEntityAttach;
#[path = "SPacketEntityEquipment.rs"]
pub mod SPacketEntityEquipment;
#[path = "SPacketEntityHeadLook.rs"]
pub mod SPacketEntityHeadLook;
#[path = "SPacketEntityMetadata.rs"]
pub mod SPacketEntityMetadata;
#[path = "SPacketEntityStatus.rs"]
pub mod SPacketEntityStatus;
#[path = "SPacketEntityTeleport.rs"]
pub mod SPacketEntityTeleport;
#[path = "SPacketEntityVelocity.rs"]
pub mod SPacketEntityVelocity;
#[path = "SPacketHeldItemChange.rs"]
pub mod SPacketHeldItemChange;
#[path = "SPacketJoinGame.rs"]
pub mod SPacketJoinGame;
#[path = "SPacketKeepAlive.rs"]
pub mod SPacketKeepAlive;
#[path = "SPacketMaps.rs"]
pub mod SPacketMaps;
#[path = "SPacketMoveVehicle.rs"]
pub mod SPacketMoveVehicle;
#[path = "SPacketMultiBlockChange.rs"]
pub mod SPacketMultiBlockChange;
#[path = "SPacketOpenWindow.rs"]
pub mod SPacketOpenWindow;
#[path = "SPacketParticles.rs"]
pub mod SPacketParticles;
#[path = "SPacketPlayerListItem.rs"]
pub mod SPacketPlayerListItem;
#[path = "SPacketPlayerPosLook.rs"]
pub mod SPacketPlayerPosLook;
#[path = "SPacketRemoveEntityEffect.rs"]
pub mod SPacketRemoveEntityEffect;
#[path = "SPacketRespawn.rs"]
pub mod SPacketRespawn;
#[path = "SPacketSetPassengers.rs"]
pub mod SPacketSetPassengers;
#[path = "SPacketSetSlot.rs"]
pub mod SPacketSetSlot;
#[path = "SPacketSpawnExperienceOrb.rs"]
pub mod SPacketSpawnExperienceOrb;
#[path = "SPacketSpawnGlobalEntity.rs"]
pub mod SPacketSpawnGlobalEntity;
#[path = "SPacketSpawnMob.rs"]
pub mod SPacketSpawnMob;
#[path = "SPacketSpawnObject.rs"]
pub mod SPacketSpawnObject;
#[path = "SPacketSpawnPainting.rs"]
pub mod SPacketSpawnPainting;
#[path = "SPacketSpawnPlayer.rs"]
pub mod SPacketSpawnPlayer;
#[path = "SPacketTimeUpdate.rs"]
pub mod SPacketTimeUpdate;
#[path = "SPacketUnloadChunk.rs"]
pub mod SPacketUnloadChunk;
#[path = "SPacketUpdateHealth.rs"]
pub mod SPacketUpdateHealth;
#[path = "SPacketWindowItems.rs"]
pub mod SPacketWindowItems;
#[path = "SPacketWindowProperty.rs"]
pub mod SPacketWindowProperty;

#[path = "SPacketConfirmTransaction.rs"]
pub mod SPacketConfirmTransaction;

#[path = "SPacketChangeGameState.rs"]
pub mod SPacketChangeGameState;
#[path = "SPacketPlayerAbilities.rs"]
pub mod SPacketPlayerAbilities;
#[path = "SPacketSetExperience.rs"]
pub mod SPacketSetExperience;
#[path = "SPacketSignEditorOpen.rs"]
pub mod SPacketSignEditorOpen;

#[path = "SPacketPlayerListHeaderFooter.rs"]
pub mod SPacketPlayerListHeaderFooter;
#[path = "SPacketTitle.rs"]
pub mod SPacketTitle;

#[path = "SPacketChat.rs"]
pub mod SPacketChat;
#[path = "SPacketCombatEvent.rs"]
pub mod SPacketCombatEvent;
#[path = "SPacketDisplayObjective.rs"]
pub mod SPacketDisplayObjective;
#[path = "SPacketScoreboardObjective.rs"]
pub mod SPacketScoreboardObjective;
#[path = "SPacketTabComplete.rs"]
pub mod SPacketTabComplete;
#[path = "SPacketTeams.rs"]
pub mod SPacketTeams;
#[path = "SPacketUpdateBossInfo.rs"]
pub mod SPacketUpdateBossInfo;
#[path = "SPacketUpdateScore.rs"]
pub mod SPacketUpdateScore;
#[path = "SPacketUpdateTileEntity.rs"]
pub mod SPacketUpdateTileEntity;

#[path = "SPacketEntityEffect.rs"]
pub mod SPacketEntityEffect;
#[path = "SPacketEntityProperties.rs"]
pub mod SPacketEntityProperties;
#[path = "SPacketServerDifficulty.rs"]
pub mod SPacketServerDifficulty;

#[path = "SPacketCustomPayload.rs"]
pub mod SPacketCustomPayload;
#[path = "SPacketPlaceGhostRecipe.rs"]
pub mod SPacketPlaceGhostRecipe;
#[path = "SPacketRecipeBook.rs"]
pub mod SPacketRecipeBook;
#[path = "SPacketUseBed.rs"]
pub mod SPacketUseBed;

#[path = "SPacketCustomSound.rs"]
pub mod SPacketCustomSound;

#[path = "SPacketSoundEffect.rs"]
pub mod SPacketSoundEffect;

#[path = "SPacketEffect.rs"]
pub mod SPacketEffect;
#[path = "SPacketSpawnPosition.rs"]
pub mod SPacketSpawnPosition;
