use crate::net::minecraft::item::ItemStack::ItemStack;
use crate::net::minecraft::nbt::NBTBase::{NBTBase, TAG_COMPOUND, TAG_INT, TAG_LIST, TAG_STRING};
use crate::net::minecraft::world::ColorizerFoliage::ColorizerFoliage;
use crate::net::minecraft::world::ColorizerGrass::ColorizerGrass;

/// MCP 1.12.2 `ItemColors` registrations used by `RenderItem`.
///
/// The handler selection, tint-index rules, NBT paths and vanilla registry
/// colours mirror `ItemColors.init`, `PotionUtils.func_190932_c`,
/// `ItemArmor.getColor`, `ItemFireworkCharge.getExplosionTag`,
/// `ItemMonsterPlacer.func_190908_h`, and `ItemMap.func_190907_h`.
#[derive(Debug, Clone)]
pub struct ItemColors {
    inventoryGrassColor: i32,
}

impl ItemColors {
    pub const DEFAULT_COLOR: i32 = -1;

    pub fn new(grass: &ColorizerGrass) -> Self {
        Self {
            inventoryGrassColor: grass.getGrassColor(0.5, 1.0),
        }
    }

    pub fn getColorFromItemstack(&self, stack: &ItemStack, tintIndex: i32) -> i32 {
        if stack.isEmpty() {
            return Self::DEFAULT_COLOR;
        }
        match stack.itemId {
            // Items.LEATHER_HELMET/CHESTPLATE/LEGGINGS/BOOTS.
            298..=301 => {
                if tintIndex > 0 {
                    Self::DEFAULT_COLOR
                } else {
                    leather_color(stack)
                }
            }
            // Blocks.DOUBLE_PLANT. Only double grass and double fern are tinted.
            175 => match stack.itemDamage & 7 {
                2 | 3 => self.inventoryGrassColor,
                _ => Self::DEFAULT_COLOR,
            },
            // Items.FIREWORK_CHARGE.
            402 => {
                if tintIndex == 1 {
                    firework_charge_color(stack)
                } else {
                    Self::DEFAULT_COLOR
                }
            }
            // Items.POTIONITEM, Items.SPLASH_POTION, Items.LINGERING_POTION.
            373 | 438 | 441 => {
                if tintIndex > 0 {
                    Self::DEFAULT_COLOR
                } else {
                    potion_color(stack)
                }
            }
            // Items.SPAWN_EGG.
            383 => spawn_egg_color(stack, tintIndex),
            // ItemBlock registrations in ItemColors.init.
            2 | 18 | 31 | 106 | 111 | 161 => self.block_item_color(stack),
            // Items.TIPPED_ARROW.
            440 => {
                if tintIndex == 0 {
                    potion_color(stack)
                } else {
                    Self::DEFAULT_COLOR
                }
            }
            // Items.FILLED_MAP.
            358 => {
                if tintIndex == 0 {
                    Self::DEFAULT_COLOR
                } else {
                    filled_map_color(stack)
                }
            }
            _ => Self::DEFAULT_COLOR,
        }
    }

    fn block_item_color(&self, stack: &ItemStack) -> i32 {
        match stack.itemId {
            // Blocks.GRASS: BlockColors' null-world inventory fallback.
            2 => self.inventoryGrassColor,
            // Blocks.TALLGRASS: dead bush is white; grass and fern use grass colormap.
            31 => {
                if stack.itemDamage & 3 == 0 {
                    0xFF_FFFF
                } else {
                    self.inventoryGrassColor
                }
            }
            // Blocks.VINE.
            106 => ColorizerFoliage::getFoliageColorBasic(),
            // Blocks.LEAVES: oak/jungle basic, spruce/birch fixed.
            18 => match stack.itemDamage & 3 {
                1 => ColorizerFoliage::getFoliageColorPine(),
                2 => ColorizerFoliage::getFoliageColorBirch(),
                _ => ColorizerFoliage::getFoliageColorBasic(),
            },
            // Blocks.LEAVES2.
            161 => ColorizerFoliage::getFoliageColorBasic(),
            // Blocks.WATERLILY null-world inventory fallback.
            111 => 7_455_580,
            _ => Self::DEFAULT_COLOR,
        }
    }
}

fn leather_color(stack: &ItemStack) -> i32 {
    let Some(root) = &stack.tagCompound else {
        return 10_511_680;
    };
    if !root.hasKeyWithType("display", TAG_COMPOUND) {
        return 10_511_680;
    }
    let display = root.getCompoundTag("display");
    if display.hasKeyWithType("color", TAG_INT) {
        display.getInteger("color")
    } else {
        10_511_680
    }
}

fn firework_charge_color(stack: &ItemStack) -> i32 {
    let Some(root) = &stack.tagCompound else {
        return 9_079_434;
    };
    if !root.hasKeyWithType("Explosion", TAG_COMPOUND) {
        return 9_079_434;
    }
    let explosion = root.getCompoundTag("Explosion");
    let Some(NBTBase::IntArray(colors)) = explosion.getTag("Colors") else {
        return 9_079_434;
    };
    if colors.len() == 1 {
        return colors[0];
    }
    // Vanilla assumes a non-empty array here. Network/NBT data generated by
    // ItemFireworkCharge satisfies that invariant; retain a safe fallback for
    // malformed third-party server data rather than panicking on division by 0.
    if colors.is_empty() {
        return 9_079_434;
    }
    let mut red = 0_i64;
    let mut green = 0_i64;
    let mut blue = 0_i64;
    for color in colors {
        red += ((color & 0xFF_0000) >> 16) as i64;
        green += ((color & 0x00_FF00) >> 8) as i64;
        blue += (color & 0x00_00FF) as i64;
    }
    let length = colors.len() as i64;
    ((red / length) as i32) << 16 | ((green / length) as i32) << 8 | (blue / length) as i32
}

fn potion_color(stack: &ItemStack) -> i32 {
    let tag = stack.tagCompound.as_ref();
    if let Some(tag) = tag {
        if tag.hasKeyWithType("CustomPotionColor", 99) {
            return tag.getInteger("CustomPotionColor");
        }
    }

    let potion_name = tag
        .filter(|tag| tag.hasKeyWithType("Potion", TAG_STRING))
        .map(|tag| normalize_resource_location(&tag.getString("Potion")))
        .unwrap_or_else(|| "minecraft:empty".to_owned());

    // PotionUtils returns the special EMPTY colour before merging custom
    // potion effects.
    if potion_name == "minecraft:empty" || potion_type_color(&potion_name).is_none() {
        return 16_253_176;
    }

    let mut effects = Vec::<PotionColorEffect>::new();
    if let Some((potion_id, amplifier)) = potion_type_effect(&potion_name) {
        if let Some(color) = potion_effect_color(potion_id) {
            effects.push(PotionColorEffect {
                color,
                amplifier,
                showParticles: true,
            });
        }
    }

    if let Some(tag) = tag {
        if tag.hasKeyWithType("CustomPotionEffects", TAG_LIST) {
            let custom = tag.getTagList("CustomPotionEffects", TAG_COMPOUND);
            for index in 0..custom.tagCount() {
                let effect = custom.getCompoundTagAt(index);
                let potion_id = effect.getByte("Id") as i32;
                let Some(color) = potion_effect_color(potion_id) else {
                    continue;
                };
                let amplifier = (effect.getByte("Amplifier") as i32).max(0);
                let show_particles = if effect.hasKeyWithType("ShowParticles", 1) {
                    effect.getBoolean("ShowParticles")
                } else {
                    true
                };
                effects.push(PotionColorEffect {
                    color,
                    amplifier,
                    showParticles: show_particles,
                });
            }
        }
    }

    if effects.is_empty() {
        // WATER/MUNDANE/THICK/AWKWARD have no effects but are not EMPTY.
        return potion_type_color(&potion_name).unwrap_or(3_694_022);
    }
    potion_effect_list_color(&effects)
}

#[derive(Debug, Clone, Copy)]
struct PotionColorEffect {
    color: i32,
    amplifier: i32,
    showParticles: bool,
}

fn potion_effect_list_color(effects: &[PotionColorEffect]) -> i32 {
    let mut red = 0.0_f32;
    let mut green = 0.0_f32;
    let mut blue = 0.0_f32;
    let mut weight = 0_i32;
    for effect in effects
        .iter()
        .copied()
        .filter(|effect| effect.showParticles)
    {
        let effect_weight = effect.amplifier + 1;
        red += (effect_weight * ((effect.color >> 16) & 0xFF)) as f32 / 255.0;
        green += (effect_weight * ((effect.color >> 8) & 0xFF)) as f32 / 255.0;
        blue += (effect_weight * (effect.color & 0xFF)) as f32 / 255.0;
        weight += effect_weight;
    }
    if weight == 0 {
        0
    } else {
        ((red / weight as f32 * 255.0) as i32) << 16
            | ((green / weight as f32 * 255.0) as i32) << 8
            | (blue / weight as f32 * 255.0) as i32
    }
}

fn potion_type_effect(name: &str) -> Option<(i32, i32)> {
    let path = name.strip_prefix("minecraft:").unwrap_or(name);
    let amplifier = if path.starts_with("strong_") { 1 } else { 0 };
    let base = path
        .strip_prefix("long_")
        .or_else(|| path.strip_prefix("strong_"))
        .unwrap_or(path);
    let id = match base {
        "night_vision" => 16,
        "invisibility" => 14,
        "leaping" => 8,
        "fire_resistance" => 12,
        "swiftness" => 1,
        "slowness" => 2,
        "water_breathing" => 13,
        "healing" => 6,
        "harming" => 7,
        "poison" => 19,
        "regeneration" => 10,
        "strength" => 5,
        "weakness" => 18,
        "luck" => 26,
        _ => return None,
    };
    Some((id, amplifier))
}

fn potion_effect_color(id: i32) -> Option<i32> {
    Some(match id {
        1 => 8_171_462,
        2 => 5_926_017,
        3 => 14_270_531,
        4 => 4_866_583,
        5 => 9_643_043,
        6 => 16_262_179,
        7 => 4_393_481,
        8 => 2_293_580,
        9 => 5_578_058,
        10 => 13_458_603,
        11 => 10_044_730,
        12 => 14_981_690,
        13 => 3_035_801,
        14 => 8_356_754,
        15 => 2_039_587,
        16 => 2_039_713,
        17 => 5_797_459,
        18 => 4_738_376,
        19 => 5_149_489,
        20 => 3_484_199,
        21 => 16_284_963,
        22 => 2_445_989,
        23 => 16_262_179,
        24 => 9_740_385,
        25 => 13_565_951,
        26 => 3_381_504,
        27 => 12_624_973,
        _ => return None,
    })
}

fn potion_type_color(name: &str) -> Option<i32> {
    POTION_TYPE_COLORS
        .iter()
        .find_map(|(key, color)| (*key == name).then_some(*color))
}

fn spawn_egg_color(stack: &ItemStack, tint_index: i32) -> i32 {
    let Some(root) = &stack.tagCompound else {
        return ItemColors::DEFAULT_COLOR;
    };
    if !root.hasKeyWithType("EntityTag", TAG_COMPOUND) {
        return ItemColors::DEFAULT_COLOR;
    }
    let entity_tag = root.getCompoundTag("EntityTag");
    if !entity_tag.hasKeyWithType("id", TAG_STRING) {
        return ItemColors::DEFAULT_COLOR;
    }
    let id = normalize_resource_location(&entity_tag.getString("id"));
    let Some((_, primary, secondary)) = ENTITY_EGG_COLORS
        .iter()
        .find(|(key, _, _)| *key == id.as_str())
    else {
        return ItemColors::DEFAULT_COLOR;
    };
    if tint_index == 0 {
        *primary
    } else {
        *secondary
    }
}

fn filled_map_color(stack: &ItemStack) -> i32 {
    let Some(root) = &stack.tagCompound else {
        return -12_173_266;
    };
    if !root.hasKeyWithType("display", TAG_COMPOUND) {
        return -12_173_266;
    }
    let display = root.getCompoundTag("display");
    if display.hasKeyWithType("MapColor", 99) {
        (-16_777_216_i32) | (display.getInteger("MapColor") & 0xFF_FFFF)
    } else {
        -12_173_266
    }
}

fn normalize_resource_location(value: &str) -> String {
    if value.contains(':') {
        value.to_owned()
    } else {
        format!("minecraft:{value}")
    }
}

const POTION_TYPE_COLORS: &[(&str, i32)] = &[
    ("minecraft:empty", 16_253_176),
    ("minecraft:water", 3_694_022),
    ("minecraft:mundane", 3_694_022),
    ("minecraft:thick", 3_694_022),
    ("minecraft:awkward", 3_694_022),
    ("minecraft:night_vision", 2_039_713),
    ("minecraft:long_night_vision", 2_039_713),
    ("minecraft:invisibility", 8_356_754),
    ("minecraft:long_invisibility", 8_356_754),
    ("minecraft:leaping", 2_293_580),
    ("minecraft:long_leaping", 2_293_580),
    ("minecraft:strong_leaping", 2_293_580),
    ("minecraft:fire_resistance", 14_981_690),
    ("minecraft:long_fire_resistance", 14_981_690),
    ("minecraft:swiftness", 8_171_462),
    ("minecraft:long_swiftness", 8_171_462),
    ("minecraft:strong_swiftness", 8_171_462),
    ("minecraft:slowness", 5_926_017),
    ("minecraft:long_slowness", 5_926_017),
    ("minecraft:water_breathing", 3_035_801),
    ("minecraft:long_water_breathing", 3_035_801),
    ("minecraft:healing", 16_262_179),
    ("minecraft:strong_healing", 16_262_179),
    ("minecraft:harming", 4_393_481),
    ("minecraft:strong_harming", 4_393_481),
    ("minecraft:poison", 5_149_489),
    ("minecraft:long_poison", 5_149_489),
    ("minecraft:strong_poison", 5_149_489),
    ("minecraft:regeneration", 13_458_603),
    ("minecraft:long_regeneration", 13_458_603),
    ("minecraft:strong_regeneration", 13_458_603),
    ("minecraft:strength", 9_643_043),
    ("minecraft:long_strength", 9_643_043),
    ("minecraft:strong_strength", 9_643_043),
    ("minecraft:weakness", 4_738_376),
    ("minecraft:long_weakness", 4_738_376),
    ("minecraft:luck", 3_381_504),
];

const ENTITY_EGG_COLORS: &[(&str, i32, i32)] = &[
    ("minecraft:bat", 4_996_656, 986_895),
    ("minecraft:blaze", 16_167_425, 16_775_294),
    ("minecraft:cave_spider", 803_406, 11_013_646),
    ("minecraft:chicken", 10_592_673, 16_711_680),
    ("minecraft:cow", 4_470_310, 10_592_673),
    ("minecraft:creeper", 894_731, 0),
    ("minecraft:donkey", 5_457_209, 8_811_878),
    ("minecraft:elder_guardian", 13_552_826, 7_632_531),
    ("minecraft:enderman", 1_447_446, 0),
    ("minecraft:endermite", 1_447_446, 7_237_230),
    ("minecraft:evocation_illager", 9_804_699, 1_973_274),
    ("minecraft:ghast", 16_382_457, 12_369_084),
    ("minecraft:guardian", 5_931_634, 15_826_224),
    ("minecraft:horse", 12_623_485, 15_656_192),
    ("minecraft:husk", 7_958_625, 15_125_652),
    ("minecraft:llama", 12_623_485, 10_051_392),
    ("minecraft:magma_cube", 3_407_872, 16_579_584),
    ("minecraft:mooshroom", 10_489_616, 12_040_119),
    ("minecraft:mule", 1_769_984, 5_321_501),
    ("minecraft:ocelot", 15_720_061, 5_653_556),
    ("minecraft:parrot", 894_731, 16_711_680),
    ("minecraft:pig", 15_771_042, 14_377_823),
    ("minecraft:polar_bear", 15_921_906, 9_803_152),
    ("minecraft:rabbit", 10_051_392, 7_555_121),
    ("minecraft:sheep", 15_198_183, 16_758_197),
    ("minecraft:shulker", 9_725_844, 5_060_690),
    ("minecraft:silverfish", 7_237_230, 3_158_064),
    ("minecraft:skeleton", 12_698_049, 4_802_889),
    ("minecraft:skeleton_horse", 6_842_447, 15_066_584),
    ("minecraft:slime", 5_349_438, 8_306_542),
    ("minecraft:spider", 3_419_431, 11_013_646),
    ("minecraft:squid", 2_243_405, 7_375_001),
    ("minecraft:stray", 6_387_319, 14_543_594),
    ("minecraft:vex", 8_032_420, 15_265_265),
    ("minecraft:villager", 5_651_507, 12_422_002),
    ("minecraft:vindication_illager", 9_804_699, 2_580_065),
    ("minecraft:witch", 3_407_872, 5_349_438),
    ("minecraft:wither_skeleton", 1_315_860, 4_672_845),
    ("minecraft:wolf", 14_144_467, 13_545_366),
    ("minecraft:zombie", 44_975, 7_969_893),
    ("minecraft:zombie_horse", 3_232_308, 9_945_732),
    ("minecraft:zombie_pigman", 15_373_203, 5_009_705),
    ("minecraft:zombie_villager", 5_651_507, 7_969_893),
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::net::minecraft::nbt::NBTTagCompound::NBTTagCompound;

    fn item(item_id: i16, damage: i16, tag: Option<NBTTagCompound>) -> ItemStack {
        ItemStack {
            itemId: item_id,
            count: 1,
            itemDamage: damage,
            tagCompound: tag,
        }
    }

    #[test]
    fn leather_and_map_nbt_paths_match_vanilla() {
        let mut display = NBTTagCompound::new();
        display.setInteger("color", 0x123456);
        let mut root = NBTTagCompound::new();
        root.setCompoundTag("display", display);
        assert_eq!(leather_color(&item(298, 0, Some(root))), 0x123456);

        let mut display = NBTTagCompound::new();
        display.setInteger("MapColor", 0xABCDEF);
        let mut root = NBTTagCompound::new();
        root.setCompoundTag("display", display);
        assert_eq!(
            filled_map_color(&item(358, 0, Some(root))),
            -16_777_216_i32 | 0xABCDEF
        );
    }

    #[test]
    fn potion_custom_color_and_custom_effect_weighting_match_potion_utils() {
        let mut root = NBTTagCompound::new();
        root.setInteger("CustomPotionColor", 0x135724);
        assert_eq!(potion_color(&item(373, 0, Some(root))), 0x135724);

        let effects = [
            PotionColorEffect {
                color: 0xFF0000,
                amplifier: 0,
                showParticles: true,
            },
            PotionColorEffect {
                color: 0x0000FF,
                amplifier: 1,
                showParticles: true,
            },
        ];
        assert_eq!(potion_effect_list_color(&effects), 0x5500AA);
    }

    #[test]
    fn registry_tables_are_complete_for_vanilla_item_colors() {
        assert_eq!(POTION_TYPE_COLORS.len(), 37);
        assert_eq!(ENTITY_EGG_COLORS.len(), 43);
    }
}
