#[path = "CraftingManager.rs"]
pub mod CraftingManager;
#[path = "IRecipe.rs"]
pub mod IRecipe;
#[path = "Ingredient.rs"]
pub mod Ingredient;
#[path = "RecipeRegistryData.rs"]
pub mod RecipeRegistryData;
#[path = "ShapedRecipes.rs"]
pub mod ShapedRecipes;
#[path = "ShapelessRecipes.rs"]
pub mod ShapelessRecipes;
