#[path = "LayerCreeperCharge.rs"]
pub mod LayerCreeperCharge;
#[path = "LayerEndermanEyes.rs"]
pub mod LayerEndermanEyes;
#[path = "LayerHeldBlock.rs"]
pub mod LayerHeldBlock;
#[path = "LayerHeldItem.rs"]
pub mod LayerHeldItem;
#[path = "LayerLlamaDecor.rs"]
pub mod LayerLlamaDecor;
#[path = "LayerMooshroomMushroom.rs"]
pub mod LayerMooshroomMushroom;
#[path = "LayerSaddle.rs"]
pub mod LayerSaddle;
#[path = "LayerSheepWool.rs"]
pub mod LayerSheepWool;
#[path = "LayerSlimeGel.rs"]
pub mod LayerSlimeGel;
#[path = "LayerSpiderEyes.rs"]
pub mod LayerSpiderEyes;
#[path = "LayerWolfCollar.rs"]
pub mod LayerWolfCollar;

#[path = "LayerArmorBase.rs"]
pub mod LayerArmorBase;
#[path = "LayerBipedArmor.rs"]
pub mod LayerBipedArmor;
#[path = "LayerCape.rs"]
pub mod LayerCape;
#[path = "LayerElytra.rs"]
pub mod LayerElytra;

#[path = "LayerCustomHead.rs"]
pub mod LayerCustomHead;
