#[path = "EntityBoat.rs"]
pub mod EntityBoat;
#[path = "EntityEnderCrystal.rs"]
pub mod EntityEnderCrystal;
#[path = "EntityItemFrame.rs"]
pub mod EntityItemFrame;
#[path = "EntityMinecart.rs"]
pub mod EntityMinecart;
#[path = "EntityPainting.rs"]
pub mod EntityPainting;
