#[path = "DefaultPlayerSkin.rs"]
pub mod DefaultPlayerSkin;
#[path = "FileResourcePack.rs"]
pub mod FileResourcePack;
#[path = "FolderResourcePack.rs"]
pub mod FolderResourcePack;
#[path = "Language.rs"]
pub mod Language;
#[path = "LanguageManager.rs"]
pub mod LanguageManager;
#[path = "Locale.rs"]
pub mod Locale;
#[path = "ResourcePackRepository.rs"]
pub mod ResourcePackRepository;
#[path = "SimpleReloadableResourceManager.rs"]
pub mod SimpleReloadableResourceManager;
#[path = "SkinManager.rs"]
pub mod SkinManager;
