#[path = "BlockFaceUV.rs"]
pub mod BlockFaceUV;
#[path = "FaceBakery.rs"]
pub mod FaceBakery;
#[path = "ItemCameraTransforms.rs"]
pub mod ItemCameraTransforms;
#[path = "ItemModelGenerator.rs"]
pub mod ItemModelGenerator;
#[path = "ModelBlock.rs"]
pub mod ModelBlock;
#[path = "ModelResourceLocation.rs"]
pub mod ModelResourceLocation;
#[path = "ModelRotation.rs"]
pub mod ModelRotation;
