#[path = "Container.rs"]
pub mod Container;
#[path = "ContainerPlayer.rs"]
pub mod ContainerPlayer;
#[path = "EntityEquipment.rs"]
pub mod EntityEquipment;
#[path = "EntityEquipmentSlot.rs"]
pub mod EntityEquipmentSlot;

#[path = "ClickType.rs"]
pub mod ClickType;
#[path = "ContainerChest.rs"]
pub mod ContainerChest;

#[path = "ContainerBeacon.rs"]
pub mod ContainerBeacon;
#[path = "ContainerBrewingStand.rs"]
pub mod ContainerBrewingStand;
#[path = "ContainerDispenser.rs"]
pub mod ContainerDispenser;
#[path = "ContainerEnchantment.rs"]
pub mod ContainerEnchantment;
#[path = "ContainerFurnace.rs"]
pub mod ContainerFurnace;
#[path = "ContainerHopper.rs"]
pub mod ContainerHopper;
#[path = "ContainerHorseInventory.rs"]
pub mod ContainerHorseInventory;
#[path = "ContainerMerchant.rs"]
pub mod ContainerMerchant;
#[path = "ContainerRepair.rs"]
pub mod ContainerRepair;
#[path = "ContainerShulkerBox.rs"]
pub mod ContainerShulkerBox;
#[path = "ContainerWindow.rs"]
pub mod ContainerWindow;
#[path = "ContainerWorkbench.rs"]
pub mod ContainerWorkbench;
#[path = "InventoryMerchant.rs"]
pub mod InventoryMerchant;
#[path = "OpenContainer.rs"]
pub mod OpenContainer;
pub mod SlotShulkerBox;
