#[path = "Render.rs"]
pub mod Render;
#[path = "RenderAbstractHorse.rs"]
pub mod RenderAbstractHorse;
#[path = "RenderArmorStand.rs"]
pub mod RenderArmorStand;
#[path = "RenderArrow.rs"]
pub mod RenderArrow;
#[path = "RenderBlaze.rs"]
pub mod RenderBlaze;
#[path = "RenderBoat.rs"]
pub mod RenderBoat;
pub mod RenderCaveSpider;
#[path = "RenderChicken.rs"]
pub mod RenderChicken;
#[path = "RenderCow.rs"]
pub mod RenderCow;
#[path = "RenderCreeper.rs"]
pub mod RenderCreeper;
#[path = "RenderDragon.rs"]
pub mod RenderDragon;
#[path = "RenderEnderman.rs"]
pub mod RenderEnderman;
#[path = "RenderEntityItem.rs"]
pub mod RenderEntityItem;
#[path = "RenderEvoker.rs"]
pub mod RenderEvoker;
#[path = "RenderFallingBlock.rs"]
pub mod RenderFallingBlock;
#[path = "RenderGhast.rs"]
pub mod RenderGhast;
#[path = "RenderGuardian.rs"]
pub mod RenderGuardian;
#[path = "RenderHorse.rs"]
pub mod RenderHorse;
#[path = "RenderIllusionIllager.rs"]
pub mod RenderIllusionIllager;
#[path = "RenderItemFrame.rs"]
pub mod RenderItemFrame;
#[path = "RenderLeashKnot.rs"]
pub mod RenderLeashKnot;
#[path = "RenderLivingBase.rs"]
pub mod RenderLivingBase;
#[path = "RenderLlama.rs"]
pub mod RenderLlama;
#[path = "RenderMagmaCube.rs"]
pub mod RenderMagmaCube;
#[path = "RenderManager.rs"]
pub mod RenderManager;
#[path = "RenderMinecart.rs"]
pub mod RenderMinecart;
#[path = "RenderMooshroom.rs"]
pub mod RenderMooshroom;
#[path = "RenderOcelot.rs"]
pub mod RenderOcelot;
#[path = "RenderPainting.rs"]
pub mod RenderPainting;
#[path = "RenderPig.rs"]
pub mod RenderPig;
#[path = "RenderPlayer.rs"]
pub mod RenderPlayer;
#[path = "RenderPolarBear.rs"]
pub mod RenderPolarBear;
#[path = "RenderRabbit.rs"]
pub mod RenderRabbit;
#[path = "RenderSheep.rs"]
pub mod RenderSheep;
#[path = "RenderShulker.rs"]
pub mod RenderShulker;
#[path = "RenderShulkerBullet.rs"]
pub mod RenderShulkerBullet;
#[path = "RenderSkeleton.rs"]
pub mod RenderSkeleton;
#[path = "RenderSlime.rs"]
pub mod RenderSlime;
#[path = "RenderSnowball.rs"]
pub mod RenderSnowball;
#[path = "RenderSpider.rs"]
pub mod RenderSpider;
#[path = "RenderSquid.rs"]
pub mod RenderSquid;
#[path = "RenderTNTPrimed.rs"]
pub mod RenderTNTPrimed;
#[path = "RenderVillager.rs"]
pub mod RenderVillager;
#[path = "RenderVindicator.rs"]
pub mod RenderVindicator;
#[path = "RenderWitch.rs"]
pub mod RenderWitch;
#[path = "RenderWolf.rs"]
pub mod RenderWolf;
#[path = "RenderXPOrb.rs"]
pub mod RenderXPOrb;
#[path = "RenderZombie.rs"]
pub mod RenderZombie;
#[path = "RenderZombieVillager.rs"]
pub mod RenderZombieVillager;
pub mod layers;

#[path = "RenderDragonFireball.rs"]
pub mod RenderDragonFireball;
#[path = "RenderFireball.rs"]
pub mod RenderFireball;
#[path = "RenderWitherSkull.rs"]
pub mod RenderWitherSkull;

#[path = "RenderFish.rs"]
pub mod RenderFish;

#[path = "RenderAreaEffectCloud.rs"]
pub mod RenderAreaEffectCloud;
#[path = "RenderEnderCrystal.rs"]
pub mod RenderEnderCrystal;
